{{- if $.Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "maira.api.fullname" . }}-config"
  labels:
{{ include "maira.api.labels" . | indent 4 }}
data:
  config.yml: |-
    grpc_listen_addr: :{{ .Values.api.grpcPort }}
    rest_listen_addr: :{{ .Values.api.apiPort }}
    max_message_size_bytes: 500000000
    server_cert: /certs/server.crt
    server_key: /certs/server.key
    workflow_server: "{{ .Values.temporal.host }}:{{ .Values.temporal.port }}"
    slack:
      bot_server: "{{ .Values.slack.bot_server }}"
      maira_client_id: "{{ .Values.slack.maira_client_id }}"
      maira_oauth_key: "{{ .Values.slack.maira_oauth_key }}"
      slack_client_id: "{{ .Values.slack.slack_client_id }}"
      slack_oauth_key: "{{ .Values.slack.slack_oauth_key }}"
      slack_signing_secret: "{{ .Values.slack.slack_signing_secret }}"
      log_level: info
{{- end }}
