{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "maira.api.fullname" . }}
  labels:
{{ include "maira.api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "maira.api.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "maira.api.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "maira.serviceAccountName" . }}
      containers:
      - name:  api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
        command: ["/apiserver"]
        args: ["-c", "/config/config.yml"]
        volumeMounts:
        - name: tls-cert
          mountPath: "/certs"
          readOnly: true
        # This is needed to sync the k8s secret with gcp secrets
        - name: tls-gcp-secret
          mountPath: "/var/tls-gcp-secret"
          readOnly: true
        - name: config-yml
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: tls-cert
        secret:
          secretName: "{{ template "maira.fullname" . }}-tls-secret"
          items:
            - key: tls.key
              path: server.key
            - key: tls.crt
              path: server.crt
      # This is needed to sync the k8s secret with gcp secrets
      - name: tls-gcp-secret
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ template "maira.fullname" . }}-tls-secretprovider
      - name: config-yml
        configMap:
          name: "{{ template "maira.api.fullname" . }}-config"
{{- end }}
