{{- if $.Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "maira.api.fullname" . }}-config"
  labels:
{{ include "maira.api.labels" . | indent 4 }}
data:
  config.yml: |-
    grpc_listen_addr: :{{ .Values.api.grpcPort }}
    rest_listen_addr: :{{ .Values.api.apiPort }}
    max_message_size_bytes: 500000000
    auth_disabled: {{ include "maira.api.auth_disabled" . }}
    auth0_tenant: "{{ .Values.api.auth0_tenant }}"
    server_cert: /certs/server.crt
    server_key: /certs/server.key
    default_tenant: "{{ .Values.api.default_tenant }}"
    admin_user_email: "{{ .Values.api.admin_user_email }}"
    workflow_server: "{{ .Values.temporal.host }}:{{ .Values.temporal.port }}"
    slack:
      bot_server: "{{ .Values.slack.bot_server }}"
      slack_client_id: "{{ .Values.slack.slack_client_id }}"
      slack_oauth_key: "{{ .Values.slack.slack_oauth_key }}"
      slack_signing_secret: "{{ .Values.slack.slack_signing_secret }}"
      socket_mode: "{{ .Values.slack.socket_mode }}"
      slack_bot_token: "{{ .Values.slack.slack_bot_token }}"
      slack_app_token: "{{ .Values.slack.slack_app_token }}"
      log_level: info
{{- end }}
