{{- if $.Values.cloud_worker.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "maira.cloud_worker.fullname" . }}-secret"
  labels:
{{ include "maira.cloud_worker.labels" . | indent 4 }}
type: Opaque
data:
  email_password: {{ .Values.cloud_worker.email.password | b64enc | quote }}
{{- end }}
