{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maira-events
  labels:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/events"
    nginx.org/ssl-services: maira-ui
spec:
  ingressClassName: nginx
  rules:
  - host: maira-ui.localdev.me
    http:
      paths:
      - backend:
          service:
            name: maira-api
            port:
              number: 443
        path: /api/events
        pathType: Prefix
  - http:
      paths:
      - backend:
          service:
            name: maira-api
            port:
              number: 443
        path: /api/events
        pathType: Prefix
{{- end }}
