{{- if $.Values.mongodb.gcp.db_uri_secret_name -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "maira.fullname" . }}-db-uri-secretprovider
  labels:
{{ include "maira.labels" . | indent 4 }}
spec:
  provider: gcp
  secretObjects:
  - secretName: {{ template "maira.fullname" . }}-db-uri-secret
    type: Opaque
    data:
    - objectName: db_uri
      key: db_uri
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.gcp.project_id }}/secrets/{{ .Values.mongodb.gcp.db_uri_secret_name}}/versions/latest"
        fileName: "db_uri"
{{- end -}}
