{{- if and .Values.mongodb.host .Values.mongodb.username .Values.mongodb.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "maira.fullname" . }}-db-uri-secret
  labels:
{{ include "maira.labels" . | indent 4 }}
type: Opaque
data:
  db_uri: {{ printf "mongodb+srv://%s:%s@%s/generated?retryWrites=true&w=majority" .Values.mongodb.username .Values.mongodb.password .Values.mongodb.host | b64enc | quote }}
{{- end }}
