{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "maira.serviceAccountName" . }}
  labels:
{{ include "maira.labels" . | indent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.gcp.service_account }}@{{ .Values.gcp.project_id }}.iam.gserviceaccount.com"
{{- end -}}
