{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "maira.serviceAccountName" . }}
  labels:
{{ include "maira.labels" . | indent 4 }}
{{- end -}}
