{{- if .Values.tls.enabled -}}
{{- if .Values.tls.key -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ template "maira.fullname" . }}-tls-secret"
  labels:
{{ include "maira.labels" . | indent 4 }}
data:
  # the data is abbreviated in this example
  tls.crt: |
    {{ .Values.tls.cert | b64enc | nindent 4 }}
  tls.key: |
    {{ .Values.tls.key | b64enc | nindent 4 }}
{{- end -}}
{{- end }}
