{{- if .Values.tls.enabled -}}
{{- if .Values.tls.gcp.key_secret_name -}}
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: {{ template "maira.fullname" . }}-tls-secretprovider
  labels:
{{ include "maira.labels" . | indent 4 }}
spec:
  provider: gcp
  secretObjects:
  - secretName: {{ template "maira.fullname" . }}-tls-secret
    type: kubernetes.io/tls
    data: 
    - objectName: key
      key: tls.key
    - objectName: cert
      key: tls.crt
  parameters:
    secrets: |
      - resourceName: "projects/{{ .Values.gcp.project_id }}/secrets/{{ .Values.tls.gcp.key_secret_name}}/versions/latest"
        fileName: "key"
      - resourceName: "projects/{{ .Values.gcp.project_id }}/secrets/{{ .Values.tls.gcp.cert_secret_name}}/versions/latest"
        fileName: "cert"
{{- end -}}

{{- end -}}
